using DL;
using Interfaces;
using Models;

namespace BL
{
    public class BudgetBL : IBudgetBL
    {
        private readonly IBudgetDL _budgetDL;
        private readonly IFixedExpenseDL _fixedExpenseDL;
        private readonly ISavingsHistoryDL _savingsHistoryDL;
        public BudgetBL(IBudgetDL budgetDL, IFixedExpenseDL fixedExpenseDL, ISavingsHistoryDL savingsHistoryDL)
        {
            _budgetDL = budgetDL;
            _fixedExpenseDL = fixedExpenseDL;
            _savingsHistoryDL = savingsHistoryDL;
        }
        
        public async Task CreateBudgetAsync(BudgetRequest request)
        {
            var budget = null as Budget;
            try
            {
                var fixedExpenses = request.fixedExpenses;
                if (fixedExpenses != null && fixedExpenses.Count > 0)
                {
                    budget = new Budget
                    {
                        user_id = Guid.Parse("a54182db-cb26-4f43-abb7-abad3c04e6f5"),
                        budget_name = request.budget_name,
                        start_date = request.start_date.AddDays(1),
                        end_date = request.end_date.AddDays(1),
                        target_amount = request.target_amount,
                        frequency = request.budget_frequency,
                        budget_type = request.budget_type,
                        income_id = request.income_id,
                        variable_expense = request.variableExpenses,
                        budget_amount = request.budget_amount
                    };

                    // Database generates UUID
                    Guid budgetId = await _budgetDL.CreateBudgetInDB(budget);

                    if (request.fixedExpenses != null)
                    {
                        foreach (var expense in request.fixedExpenses)
                        {
                            var fixedExpense = new FixedExpense
                            {
                                user_id = Guid.Parse("a54182db-cb26-4f43-abb7-abad3c04e6f5"),
                                budget_id = budgetId,          // <-- generated by DB
                                category_id = expense.category_id,
                                name = expense.expense_name,
                                description = expense.description
                            };

                            await _fixedExpenseDL.CreateFixedExpenseInDB(fixedExpense);
                        }
                    }
                }
                
            }
            catch (Exception e)
            {
               System.Console.WriteLine(e.Message.ToString());
            }
        }

        public async Task<List<BudgetDetails>> GetBudgetsAsync()
        {
            var list = await _budgetDL.GetBudgetsFromDB();
            return list;
        }
        
        public async Task ProcessBudgetAfterExpense(Guid incomeId)
        {
            // Get active budget for this income source

            var budget = await _budgetDL.GetBudgetsFromDB();

            if (budget == null)
                return;

            // Get dashboard

            var dashboard = budget.Where(x => x.income_id == incomeId && x.is_active && x.budget_type == "regular").FirstOrDefault();

            if (dashboard == null)
                return;

            // Already credited?

            if (!dashboard.is_active)
                return;

            // Completed?

            if ((dashboard?.budget_status?.ToUpper() == "OVERSPENT" || dashboard?.budget_status?.ToUpper() == "COMPLETED") && !dashboard.is_savings_credited)
            {
                double savingsAmount = Convert.ToDouble(dashboard?.budget_amount)  - Convert.ToDouble(dashboard?.spent_amount);
                if (savingsAmount <= 0) return;
                var savingsHistory = new SavingsHistory
                {
                    user_id = Guid.Parse("a54182db-cb26-4f43-abb7-abad3c04e6f5"),
                    budget_id = dashboard.budget_id,
                    saved_amount = savingsAmount,
                    credited_on = DateTime.UtcNow,
                    created_at = DateTime.UtcNow
                };
                
                await _savingsHistoryDL.CreateSavingsHistoryInDB(savingsHistory);
                await _budgetDL.UpdateBudgetSavingsStatus(dashboard.budget_id);
            }
        }
    }
}